Corrected Yaml file

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -26,6 +26,5 @@ jobs:
       - name: Print operating system
         run: 'echo "OS: ${{ runner.os }}"'
 
-      - name: Deliberately fail
-        run: exit 1
-        
+     # - name: Deliberately fail
+      #  run: exit 1
